version: 0.0
os: linux
files:
  - source: /*
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 400
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  
